import { Button, Eyebrow } from "../design-system";
import { site } from "../content/site";
import type { RequestKind } from "../features/requests/model";

export function LegalPage({ kind, onContact }: { kind: "privacidad" | "condiciones"; onContact: (kind: RequestKind) => void }) {
  return <main id="contenido" tabIndex={-1} className="legal-page office-container"><a href="/" className="legal-back">← Volver a la Oficina</a><Eyebrow>La Oficina de los Últimos Cuentos</Eyebrow><h1 className="office-heading">{kind === "privacidad" ? "Tu correspondencia es privada." : "Antes de enviar una consulta."}</h1><p className="office-muted">Actualizado el 13 de septiembre de 2026.</p>
    {kind === "privacidad" ? <div className="legal-copy">
      <h2>Qué nos dejás y para qué</h2><p>La Oficina de los Últimos Cuentos recibe tus datos de contacto y el contenido de tu consulta para poder responderte. Según el motivo, pedimos tu ciudad, provincia y código postal para revisar disponibilidad de envío, o los datos de tu espacio para conversar sobre distribución.</p><p>En esta etapa no pedimos domicilios particulares completos ni datos de tarjetas. Para regalar, pedimos el contacto de quien regala y la localidad de destino; no damos de alta al destinatario en una lista de mails.</p>
      <h2>Los avisos son una elección</h2><p>La casilla de avisos de encuentros empieza desmarcada. Si la elegís, registramos tu permiso junto con la fecha y el texto que aceptaste. Podés pedir la baja cuando quieras. Consultar por una carta o un espacio no te suscribe automáticamente a los avisos.</p>
      <h2>Dónde llega tu consulta</h2><p>{site.googleFormUrl ? "Los enlaces de consulta llevan a Google Forms, donde se informa el tratamiento de las respuestas. Las solicitudes de gestión de datos de esta web se reciben mediante Formspree." : "Los formularios de esta web envían la información a Formspree, el servicio que utilizamos para recibir consultas."} La Oficina accede a los datos para gestionar tu pedido. No publicamos tus respuestas ni tus datos personales en la web.</p><p>Podés consultar la <a href="https://formspree.io/legal/privacy-policy/" target="_blank" rel="noreferrer">política de privacidad de Formspree (abre otra pestaña)</a>{site.googleFormUrl && <> y la <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">de Google (abre otra pestaña)</a></>}.</p>
      <h2>Consultar, corregir o pedir una baja</h2><p>Podés pedir acceso, corrección o eliminación de los datos que nos dejaste, o la baja de los avisos. Te responderemos al mail que indiques para gestionar el pedido. No envíes contraseñas, documentos de identidad ni datos de pago en el mensaje.</p><Button variant="secondary" onClick={() => onContact("preferencias")}>Gestionar avisos y datos</Button>{site.email && <p>También podés escribir a <a href={`mailto:${site.email}`}>{site.email}</a>.</p>}
      <h2>Una presencia pequeña</h2><p>Esta web no incorpora herramientas de publicidad ni seguimiento de visitas. Los proveedores de alojamiento y de formularios pueden procesar datos técnicos necesarios para prestar sus servicios. El formulario conserva lo escrito en la pantalla durante la consulta; no lo guarda en el almacenamiento local de tu navegador.</p>
    </div> : <div className="legal-copy">
      <h2>Primero conversamos</h2><p>Por ahora esta web recibe consultas. Enviar un formulario no realiza una compra, no activa una suscripción y no reserva una entrega. Antes de coordinar un pago, confirmamos la oferta disponible, el precio, la cobertura, el costo de envío y las condiciones correspondientes.</p>
      <h2>La propuesta mensual</h2><p>La suscripción contempla una carta con un cuento cada mes y la posibilidad de enterarte de los encuentros de la Oficina. El precio, la primera entrega, la renovación y la cancelación se informan antes de contratar.</p>
      <h2>Regalar un cuento</h2><p>La consulta la hace quien regala. Coordinamos con esa persona las condiciones y el envío para conservar la sorpresa. La persona que recibe no queda suscripta a pagos ni a avisos por mail.</p>
      <h2>Focos y mensajeros</h2><p>Una propuesta de espacio se conversa antes de aparecer en la red pública. Para los mensajeros, la postulación será mediante una carta con cuento propio: publicaremos la dirección y las condiciones de selección cuando el buzón esté listo. Enviar una consulta no garantiza selección, publicación ni asignación de reparto.</p>
      <h2>Encuentros</h2><p>Publicamos cada encuentro cuando su fecha y condiciones están confirmadas. Recibir un aviso no implica entrada gratuita ni lugar reservado. Si un encuentro necesita inscripción, se explica en su ficha.</p>
      <h2>Si te queda una pregunta</h2><Button variant="secondary" onClick={() => onContact("contacto")}>Escribir a la Oficina</Button>
    </div>}
  </main>;
}
